# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Layout.ui'
#
# Created: Wed Apr 16 15:29:10 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(906, 799)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.run = QtGui.QPushButton(self.centralwidget)
        self.run.setGeometry(QtCore.QRect(10, 720, 101, 31))
        self.run.setObjectName(_fromUtf8("run"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 901, 711))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(40, 50, 71, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(40, 590, 111, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_15 = QtGui.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(40, 550, 111, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.cdom_file = QtGui.QComboBox(self.tab)
        self.cdom_file.setGeometry(QtCore.QRect(160, 500, 141, 27))
        self.cdom_file.setObjectName(_fromUtf8("cdom_file"))
        self.nb_cpu = QtGui.QComboBox(self.tab)
        self.nb_cpu.setGeometry(QtCore.QRect(160, 540, 78, 31))
        self.nb_cpu.setObjectName(_fromUtf8("nb_cpu"))
        self.graphicsView = QtGui.QGraphicsView(self.tab)
        self.graphicsView.setGeometry(QtCore.QRect(480, 20, 401, 201))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.sens = QtGui.QSlider(self.tab)
        self.sens.setEnabled(True)
        self.sens.setGeometry(QtCore.QRect(530, 230, 341, 31))
        self.sens.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.sens.setAutoFillBackground(False)
        self.sens.setOrientation(QtCore.Qt.Horizontal)
        self.sens.setObjectName(_fromUtf8("sens"))
        self.label_17 = QtGui.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(480, 240, 41, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.line = QtGui.QFrame(self.tab)
        self.line.setEnabled(True)
        self.line.setGeometry(QtCore.QRect(460, -10, 20, 691))
        self.line.setAutoFillBackground(False)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.exec_path = QtGui.QLineEdit(self.tab)
        self.exec_path.setEnabled(False)
        self.exec_path.setGeometry(QtCore.QRect(60, 620, 391, 21))
        self.exec_path.setObjectName(_fromUtf8("exec_path"))
        self.p_values = QtGui.QLineEdit(self.tab)
        self.p_values.setGeometry(QtCore.QRect(140, 50, 201, 21))
        self.p_values.setObjectName(_fromUtf8("p_values"))
        self.label_1 = QtGui.QLabel(self.tab)
        self.label_1.setGeometry(QtCore.QRect(10, 10, 241, 31))
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(40, 80, 151, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(40, 510, 91, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.x_value = QtGui.QLineEdit(self.tab)
        self.x_value.setGeometry(QtCore.QRect(140, 100, 51, 21))
        self.x_value.setObjectName(_fromUtf8("x_value"))
        self.y_value = QtGui.QLineEdit(self.tab)
        self.y_value.setGeometry(QtCore.QRect(140, 130, 51, 21))
        self.y_value.setObjectName(_fromUtf8("y_value"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(80, 100, 21, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(80, 130, 21, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(40, 160, 151, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.s_value = QtGui.QLineEdit(self.tab)
        self.s_value.setGeometry(QtCore.QRect(140, 220, 51, 21))
        self.s_value.setObjectName(_fromUtf8("s_value"))
        self.g_value = QtGui.QLineEdit(self.tab)
        self.g_value.setGeometry(QtCore.QRect(140, 180, 51, 21))
        self.g_value.setObjectName(_fromUtf8("g_value"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(80, 180, 21, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(80, 220, 21, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(40, 250, 71, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.z_value = QtGui.QLineEdit(self.tab)
        self.z_value.setGeometry(QtCore.QRect(140, 250, 51, 21))
        self.z_value.setObjectName(_fromUtf8("z_value"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(200, 250, 21, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.exec_path_button = QtGui.QPushButton(self.tab)
        self.exec_path_button.setGeometry(QtCore.QRect(160, 580, 71, 31))
        self.exec_path_button.setObjectName(_fromUtf8("exec_path_button"))
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(40, 280, 101, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.waveL_values = QtGui.QLineEdit(self.tab)
        self.waveL_values.setGeometry(QtCore.QRect(140, 280, 311, 21))
        self.waveL_values.setObjectName(_fromUtf8("waveL_values"))
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(40, 350, 191, 21))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.phyto_button = QtGui.QPushButton(self.tab)
        self.phyto_button.setGeometry(QtCore.QRect(240, 350, 71, 31))
        self.phyto_button.setObjectName(_fromUtf8("phyto_button"))
        self.phyto_path = QtGui.QLineEdit(self.tab)
        self.phyto_path.setEnabled(False)
        self.phyto_path.setGeometry(QtCore.QRect(60, 390, 391, 21))
        self.phyto_path.setObjectName(_fromUtf8("phyto_path"))
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(40, 430, 141, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.bottom_path = QtGui.QLineEdit(self.tab)
        self.bottom_path.setEnabled(False)
        self.bottom_path.setGeometry(QtCore.QRect(60, 460, 391, 20))
        self.bottom_path.setObjectName(_fromUtf8("bottom_path"))
        self.bottom_button = QtGui.QPushButton(self.tab)
        self.bottom_button.setGeometry(QtCore.QRect(240, 420, 71, 31))
        self.bottom_button.setObjectName(_fromUtf8("bottom_button"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(40, 310, 66, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.verbose_value = QtGui.QLineEdit(self.tab)
        self.verbose_value.setGeometry(QtCore.QRect(140, 310, 31, 21))
        self.verbose_value.setObjectName(_fromUtf8("verbose_value"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.ReverseTab = QtGui.QWidget()
        self.ReverseTab.setObjectName(_fromUtf8("ReverseTab"))
        self.graphicsView_2 = QtGui.QGraphicsView(self.ReverseTab)
        self.graphicsView_2.setGeometry(QtCore.QRect(480, 20, 401, 201))
        self.graphicsView_2.setObjectName(_fromUtf8("graphicsView_2"))
        self.line_2 = QtGui.QFrame(self.ReverseTab)
        self.line_2.setGeometry(QtCore.QRect(460, -10, 20, 691))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_20 = QtGui.QLabel(self.ReverseTab)
        self.label_20.setGeometry(QtCore.QRect(490, 240, 66, 17))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.McGee_radioButton = QtGui.QRadioButton(self.ReverseTab)
        self.McGee_radioButton.setGeometry(QtCore.QRect(80, 80, 116, 22))
        self.McGee_radioButton.setObjectName(_fromUtf8("McGee_radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(self.ReverseTab)
        self.radioButton_2.setGeometry(QtCore.QRect(80, 110, 116, 22))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.radioButton_3 = QtGui.QRadioButton(self.ReverseTab)
        self.radioButton_3.setGeometry(QtCore.QRect(80, 140, 116, 22))
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.label_19 = QtGui.QLabel(self.ReverseTab)
        self.label_19.setGeometry(QtCore.QRect(40, 50, 101, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_18 = QtGui.QLabel(self.ReverseTab)
        self.label_18.setGeometry(QtCore.QRect(10, 20, 191, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.x_value_reverse = QtGui.QLineEdit(self.ReverseTab)
        self.x_value_reverse.setGeometry(QtCore.QRect(620, 320, 51, 21))
        self.x_value_reverse.setObjectName(_fromUtf8("x_value_reverse"))
        self.label_27 = QtGui.QLabel(self.ReverseTab)
        self.label_27.setGeometry(QtCore.QRect(560, 440, 21, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_22 = QtGui.QLabel(self.ReverseTab)
        self.label_22.setGeometry(QtCore.QRect(520, 300, 151, 21))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_29 = QtGui.QLabel(self.ReverseTab)
        self.label_29.setGeometry(QtCore.QRect(680, 470, 21, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_24 = QtGui.QLabel(self.ReverseTab)
        self.label_24.setGeometry(QtCore.QRect(560, 350, 21, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_23 = QtGui.QLabel(self.ReverseTab)
        self.label_23.setGeometry(QtCore.QRect(560, 320, 21, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.y_value_reverse = QtGui.QLineEdit(self.ReverseTab)
        self.y_value_reverse.setGeometry(QtCore.QRect(620, 350, 51, 21))
        self.y_value_reverse.setObjectName(_fromUtf8("y_value_reverse"))
        self.label_21 = QtGui.QLabel(self.ReverseTab)
        self.label_21.setGeometry(QtCore.QRect(520, 270, 71, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_30 = QtGui.QLabel(self.ReverseTab)
        self.label_30.setGeometry(QtCore.QRect(520, 500, 101, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_25 = QtGui.QLabel(self.ReverseTab)
        self.label_25.setGeometry(QtCore.QRect(520, 380, 151, 21))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.g_value_reverse = QtGui.QLineEdit(self.ReverseTab)
        self.g_value_reverse.setGeometry(QtCore.QRect(620, 400, 51, 21))
        self.g_value_reverse.setObjectName(_fromUtf8("g_value_reverse"))
        self.p_values_reverse = QtGui.QLineEdit(self.ReverseTab)
        self.p_values_reverse.setGeometry(QtCore.QRect(620, 270, 201, 21))
        self.p_values_reverse.setObjectName(_fromUtf8("p_values_reverse"))
        self.s_value_reverse = QtGui.QLineEdit(self.ReverseTab)
        self.s_value_reverse.setGeometry(QtCore.QRect(620, 440, 51, 21))
        self.s_value_reverse.setObjectName(_fromUtf8("s_value_reverse"))
        self.label_28 = QtGui.QLabel(self.ReverseTab)
        self.label_28.setGeometry(QtCore.QRect(520, 470, 71, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.waveL_values_reverse = QtGui.QLineEdit(self.ReverseTab)
        self.waveL_values_reverse.setGeometry(QtCore.QRect(620, 500, 311, 21))
        self.waveL_values_reverse.setObjectName(_fromUtf8("waveL_values_reverse"))
        self.z_value_reverse = QtGui.QLineEdit(self.ReverseTab)
        self.z_value_reverse.setGeometry(QtCore.QRect(620, 470, 51, 21))
        self.z_value_reverse.setObjectName(_fromUtf8("z_value_reverse"))
        self.label_26 = QtGui.QLabel(self.ReverseTab)
        self.label_26.setGeometry(QtCore.QRect(560, 400, 21, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.tabWidget.addTab(self.ReverseTab, _fromUtf8(""))
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(120, 730, 241, 16))
        self.progressBar.setMouseTracking(False)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(True)
        self.progressBar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.cancel = QtGui.QPushButton(self.centralwidget)
        self.cancel.setGeometry(QtCore.QRect(370, 720, 101, 31))
        self.cancel.setObjectName(_fromUtf8("cancel"))
        self.quit = QtGui.QPushButton(self.centralwidget)
        self.quit.setGeometry(QtCore.QRect(800, 720, 101, 31))
        self.quit.setObjectName(_fromUtf8("quit"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Batch scripts and Reverse", None, QtGui.QApplication.UnicodeUTF8))
        self.run.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "P values :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Executive path :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Number of CPU :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Sens.", None, QtGui.QApplication.UnicodeUTF8))
        self.exec_path.setText(QtGui.QApplication.translate("MainWindow", "/home/boulefi/jude2_install/bin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_1.setText(QtGui.QApplication.translate("MainWindow", "Set the Bio-optical parameters list :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Particules scaterring :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "CDOM Files :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "x :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "y :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Organic absorption :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "g :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "s :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Depth (z) :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "(m)", None, QtGui.QApplication.UnicodeUTF8))
        self.exec_path_button.setText(QtGui.QApplication.translate("MainWindow", "DIrectory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Wavelengths :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Phytoplankton absorption :", None, QtGui.QApplication.UnicodeUTF8))
        self.phyto_button.setText(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.phyto_path.setText(QtGui.QApplication.translate("MainWindow", "/home/boulefi/jude2_install/bin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Bottom reflectance :", None, QtGui.QApplication.UnicodeUTF8))
        self.bottom_path.setText(QtGui.QApplication.translate("MainWindow", "/home/boulefi/jude2_install/bin", None, QtGui.QApplication.UnicodeUTF8))
        self.bottom_button.setText(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Verbose :", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Details :", None, QtGui.QApplication.UnicodeUTF8))
        self.McGee_radioButton.setText(QtGui.QApplication.translate("MainWindow", "McGEE 1999", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("MainWindow", "RadioButton", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("MainWindow", "RadioButton", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Tool (method) :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Deconvolution parameters :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "s :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Particules scaterring :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "(m)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "y :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "x :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "P values :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Wavelengths :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Organic absorption :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Depth (z) :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "g :", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ReverseTab), QtGui.QApplication.translate("MainWindow", "Reverse", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.quit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))

